.eslintrc.js
.github/workflows/docker-e2e.yml
src/auth/auth.service.ts
src/auth/dto/auth-email-login.dto.ts
src/auth/dto/auth-register-login.dto.ts
src/database/migrations/1708180358731-editUserEntity.ts
src/database/seeds/relational/user/user-seed.service.ts
src/social/interfaces/social.interface.ts
src/users/domain/user.ts
src/users/dto/create-user.dto.ts
src/users/dto/update-user.dto.ts
src/users/infrastructure/persistence/relational/entities/user.entity.ts
src/users/infrastructure/persistence/relational/mappers/user.mapper.ts
src/users/users.service.ts
test/admin/auth.e2e-spec.ts
test/admin/users.e2e-spec.ts
test/user/auth.e2e-spec.ts
test/utils/constants.ts

Include username, bio, avatar, and status message

Modify user-entity

---

.eslintrc.js
src/app.module.ts
src/database/migrations/1708462643324-createWorkspace.ts
src/database/seeds/relational/run-seed.ts
src/database/seeds/relational/seed.module.ts
src/database/seeds/relational/workspace/workspace-seed.module.ts
src/database/seeds/relational/workspace/workspace-seed.service.ts
src/database/typeorm-config.service.ts
src/workspaces/domain/workspace.ts
src/workspaces/infrastructure/persistence/entities/workspace.entity.ts
src/workspaces/workspaces.controller.spec.ts
src/workspaces/workspaces.controller.ts
src/workspaces/workspaces.module.ts
src/workspaces/workspaces.service.spec.ts
src/workspaces/workspaces.service.ts

Add workspace entity

---

src/database/migrations/1708530117129-addUserWorkspaceRelationship.ts
src/database/seeds/relational/workspace/workspace-seed.service.ts
src/users/domain/user.ts
src/users/infrastructure/persistence/relational/entities/user.entity.ts
src/users/infrastructure/persistence/user.repository.ts
src/workspaces/domain/workspace.ts
src/workspaces/infrastructure/persistence/entities/workspace.entity.ts
src/workspaces/infrastructure/persistence/mappers/workspace.mapper.ts
src/workspaces/infrastructure/persistence/repositories/workspace.repository.ts

Add user/workspace relationship

---

src/workspaces/dto/create-workspace.dto.ts
src/workspaces/infrastructure/persistence/entities/workspace.entity.ts
src/workspaces/infrastructure/persistence/mappers/workspace.mapper.ts
src/workspaces/infrastructure/persistence/persistence.module.ts
src/workspaces/infrastructure/persistence/repositories/workspace.repository.ts
src/workspaces/infrastructure/persistence/workspace.repository.ts
src/workspaces/workspaces.controller.ts
src/workspaces/workspaces.module.ts
src/workspaces/workspaces.service.ts

This pull request implements soft delete functionality for the workspaces controllers.
resolves #22

feat(workspace): add soft delete functionality

---

src/workspaces/dto/create-workspace.dto.ts
src/workspaces/infrastructure/persistence/entities/workspace.entity.ts
src/workspaces/infrastructure/persistence/mappers/workspace.mapper.ts
src/workspaces/infrastructure/persistence/persistence.module.ts
src/workspaces/infrastructure/persistence/repositories/workspace.repository.ts
src/workspaces/infrastructure/persistence/workspace.repository.ts
src/workspaces/workspaces.controller.ts
src/workspaces/workspaces.module.ts
src/workspaces/workspaces.service.ts

Create workspace controller

---

src/channels/infrastructure/persistence/entities/channel.entity.ts
src/workspaces/domain/workspace.ts
src/workspaces/infrastructure/persistence/entities/workspace.entity.ts
src/workspaces/infrastructure/persistence/repositories/workspace.repository.ts
src/workspaces/infrastructure/persistence/workspace.repository.ts
src/workspaces/workspaces.controller.ts
src/workspaces/workspaces.service.ts

feat(workspace): Add get workspace channels with pagination handler

---

src/channels/channels.controller.ts
src/channels/channels.module.ts
src/channels/channels.service.ts
src/channels/dto/create-channel.dto.ts
src/channels/infrastructure/persistence/channel.repository.ts
src/channels/infrastructure/persistence/persistence.module.ts
src/channels/infrastructure/persistence/repositories/channel.repository.ts
src/users/domain/user.ts
src/users/infrastructure/persistence/relational/entities/user.entity.ts
src/workspaces/domain/workspace.ts

feat(channel): add `createChannel`

---

src/workspaces/workspaces.service.ts

Minor Refactors for error handling in workspaces Service.

refactor(workspace): Refactor error handling in WorkspacesService

---

src/workspaces/workspaces.controller.ts

fix(worksapce): make pagination options optional

---

src/channels/channels.service.ts
src/workspaces/workspaces.service.ts

As per the guidelines outlined in the RESTful API, adjustments have been made to the response codes to align with RESTful principles.

fix: update response codes to align with RESTful principles.

---

src/auth/dto/auth-email-login.dto.ts

Remove username field from Auth Email Login

---

src/channels/channels.controller.ts
src/channels/channels.module.ts
src/channels/channels.service.ts
src/users/dto/query-user.dto.ts
src/users/infrastructure/persistence/relational/repositories/user.repository.ts
src/workspaces/infrastructure/persistence/workspace.repository.ts
src/workspaces/workspaces.controller.ts
src/workspaces/workspaces.module.ts
src/workspaces/workspaces.service.ts

Refactor get x-Users

---

src/database/migrations/1710450716544-addChildsCount.ts
src/database/migrations/1710457891187-dropHasChild.ts
src/messages/domain/message.ts
src/messages/infrastructure/presistence/entities/message.entity.ts
src/messages/infrastructure/presistence/mappers/message.mapper.ts
src/messages/infrastructure/presistence/repositories/message.repository.ts
src/messages/infrastructure/presistence/subscribers/message.subscriber.ts

Add replies count to parent messages

---

src/workspaces/infrastructure/persistence/subscibers/workspace.subscriber.ts

feat(workspace): create default startup channel

---

src/auth/dto/auth-update.dto.ts
src/users/users.service.ts

feat(auth): enable email update

---

src/database/migrations/1713644842801-dropAvatarColumn.ts
src/users/dto/create-user.dto.ts
src/users/infrastructure/persistence/relational/entities/user.entity.ts

User photo

---

src/database/migrations/1713646688515-addPhotoColWorkspace.ts
src/workspaces/domain/workspace.ts
src/workspaces/dto/create-workspace.dto.ts
src/workspaces/dto/update-workspace.dto.ts
src/workspaces/infrastructure/persistence/entities/workspace.entity.ts
src/workspaces/infrastructure/persistence/mappers/workspace.mapper.ts
src/workspaces/workspaces.module.ts
src/workspaces/workspaces.service.ts

This PR enables setting and updating workspace photo
Closes #81

Add workspace photos

---

src/channels/channels.controller.ts
src/channels/domain/channel.ts
src/channels/infrastructure/persistence/entities/channel.entity.ts
src/channels/infrastructure/persistence/mappers/channel.mapper.ts
src/channels/infrastructure/persistence/repositories/channel.repository.ts

fix(channel): fix `PATCH` request on `channel`

---

src/invites/invites.service.ts

- refactor `inviteToWorkspace` function to send invitations concurrently instead of awaiting each invitation to be sent

refactor(invites): refactor `inviteToWorkspace` function

---

src/events/dto/message-updated.dto.ts
src/events/enums/events.enum.ts
src/events/events.gateway.ts
src/events/events.service.ts
src/events/exceptions/ws-catch-all.ts
src/messages/infrastructure/persistence/repositories/message.repository.ts

feat(event): add `message_updated`

---

src/events/dto/subscribe.dto.ts
src/events/enums/events.enum.ts
src/events/events.gateway.ts
src/events/events.service.ts

Add unsubscribe event

---

src/workspaces/workspaces.controller.ts

refactor(Workspace): To return `hasNextPage` property

---

src/events/dto/event.dto.ts
src/events/dto/message-deleted.dto.ts
src/events/enums/events.enum.ts
src/events/events.gateway.ts
src/events/events.service.ts

feat(events): add `message_deleted` event

---

src/events/channels.service.ts
src/events/dto/channel-updated.dto.ts
src/events/enums/events.enum.ts
src/events/events.gateway.ts

feat(event): add `channel_updated`

---

src/events/dto/workspace-updated.dto.ts
src/events/enums/events.enum.ts
src/events/events.gateway.ts
src/events/events.module.ts
src/events/workspaces.service.ts

feat(event): add `workspace_updated`
